name: Docker-compose build and push images to docker hub
on:
  push:
    branches: [ "main", "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Check docker version
      run: docker --version
    - name: Check docker-compose --version
      run: docker compose version
    - name: Docker-compose building images
      run: docker compose -f docker-compose.yml build
    - name: Listing built images from docker-compose
      run: docker images --all
  
  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: viewing all the services
      run: docker compose -f docker-compose.yml ps
    - name: pushing images
      run: docker compose push