name: Docker-compose build and push images to docker hub
on:
  push:
    branches: [ "main", "test" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Check docker version
      run: docker --version
    - name: installing docker-compose
      run: sudo apt install -y docker-compose-plugin
    - name: Check docker-compose --version
      run: docker-compose --version
    # - name: Docker-compose building images
    #   run: docker-compose build -f docker-compose.yml
    # - name: Listing built images from docker-compose
    #   run: docker images --all
    # - name: Run docker-compose
    #   uses: hoverkraft-tech/compose-action@v2.0.1
    #   with:
    #     compose-file: "./docker-compose.yml"
    # - name: Listing built images from docker-compose
    #   run: docker images --all
    # - name: Pushing all the images
    #   run: |
    #       docker-compose push